apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
  namespace: cms-emp
spec:
  backups:
    pgbackrest:
      configuration:
      - secret:
          name: pgo-s3-creds
      global:
        repo1-path: /cms-emp/hippo
        repo1-s3-uri-style: path
        repo1-storage-verify-tls: "n"
      image: devmspksharbor.in.staffservice.co.jp/library/crunchy-pgbackrest:centos8-2.36-0
      repos:
      - name: repo1
        s3:
          bucket: crunchy-wal-backup
          endpoint: nginx-rp-for-minio.pgo-star
          region: Tokyo
  databaseInitSQL:
    key: init.sql
    name: hippo-init-sql
  image: devmspksharbor.in.staffservice.co.jp/library/crunchy-postgres:centos8-13.5-0
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: csi
    name: psql-star-pg
    replicas: 1
    resources:
      limits:
        cpu: 2
        memory: 6Gi
      requests:
        cpu: 250m
        memory: 256Mi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          checkpoint_completion_target: 0.9
          default_statistics_target: 100
          default_transaction_read_only: false
          dynamic_shared_memory_type: posix
          effective_cache_size: 6GB
          effective_io_concurrency: 200
          log_connections: true
          log_destination: stderr
          logging_collector: false
          maintenance_work_mem: 512MB
          max_connections: 200
          max_wal_size: 4GB
          min_wal_size: 1GB
          random_page_cost: 1.1
          shared_buffers: 2GB
          wal_buffers: 16MB
          work_mem: 10485kB
        pg_hba:
        - local repication all   trust
        - local all all   trust
        - host replication all 127.0.0.1/32 trust
        - host replication all ::1/128 trust
        - host all all 127.0.0.1/32 trust
        - host all all 0.0.0.0/0 md5
        - host replication postgres 0.0.0.0/0 md5
  postgresVersion: 13
