apiVersion: v1
kind: Service
metadata:
  labels:
    app: cms-can-db
  name: cms-can-db
  namespace: cms-can
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgres-operator.crunchydata.com/cluster: hippo
    postgres-operator.crunchydata.com/role: master
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.23.55.66
